[project]
name = "newproject2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "fake-useragent>=2.2.0",
    "pandas>=2.3.0",
    "pre-commit>=4.2.0",
    "requests>=2.32.3",
    "ruff>=0.11.13",
]
